// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package dataplaneresource

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-azapi.dataPlaneResource.DataPlaneResource",
		reflect.TypeOf((*DataPlaneResource)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "body", GoGetter: "Body"},
			_jsii_.MemberProperty{JsiiProperty: "bodyInput", GoGetter: "BodyInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "createHeaders", GoGetter: "CreateHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "createHeadersInput", GoGetter: "CreateHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "createQueryParameters", GoGetter: "CreateQueryParameters"},
			_jsii_.MemberProperty{JsiiProperty: "createQueryParametersInput", GoGetter: "CreateQueryParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "deleteHeaders", GoGetter: "DeleteHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "deleteHeadersInput", GoGetter: "DeleteHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "deleteQueryParameters", GoGetter: "DeleteQueryParameters"},
			_jsii_.MemberProperty{JsiiProperty: "deleteQueryParametersInput", GoGetter: "DeleteQueryParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreCasing", GoGetter: "IgnoreCasing"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreCasingInput", GoGetter: "IgnoreCasingInput"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreMissingProperty", GoGetter: "IgnoreMissingProperty"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreMissingPropertyInput", GoGetter: "IgnoreMissingPropertyInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "locks", GoGetter: "Locks"},
			_jsii_.MemberProperty{JsiiProperty: "locksInput", GoGetter: "LocksInput"},
			_jsii_.MemberMethod{JsiiMethod: "markWriteOnlyAttribute", GoMethod: "MarkWriteOnlyAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "output", GoGetter: "Output"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "parentId", GoGetter: "ParentId"},
			_jsii_.MemberProperty{JsiiProperty: "parentIdInput", GoGetter: "ParentIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putRetry", GoMethod: "PutRetry"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "readHeaders", GoGetter: "ReadHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "readHeadersInput", GoGetter: "ReadHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "readQueryParameters", GoGetter: "ReadQueryParameters"},
			_jsii_.MemberProperty{JsiiProperty: "readQueryParametersInput", GoGetter: "ReadQueryParametersInput"},
			_jsii_.MemberMethod{JsiiMethod: "registerProviderFeatureUsage", GoMethod: "RegisterProviderFeatureUsage"},
			_jsii_.MemberProperty{JsiiProperty: "replaceTriggersExternalValues", GoGetter: "ReplaceTriggersExternalValues"},
			_jsii_.MemberProperty{JsiiProperty: "replaceTriggersExternalValuesInput", GoGetter: "ReplaceTriggersExternalValuesInput"},
			_jsii_.MemberProperty{JsiiProperty: "replaceTriggersRefs", GoGetter: "ReplaceTriggersRefs"},
			_jsii_.MemberProperty{JsiiProperty: "replaceTriggersRefsInput", GoGetter: "ReplaceTriggersRefsInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetBody", GoMethod: "ResetBody"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateHeaders", GoMethod: "ResetCreateHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateQueryParameters", GoMethod: "ResetCreateQueryParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeleteHeaders", GoMethod: "ResetDeleteHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeleteQueryParameters", GoMethod: "ResetDeleteQueryParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreCasing", GoMethod: "ResetIgnoreCasing"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreMissingProperty", GoMethod: "ResetIgnoreMissingProperty"},
			_jsii_.MemberMethod{JsiiMethod: "resetLocks", GoMethod: "ResetLocks"},
			_jsii_.MemberMethod{JsiiMethod: "resetName", GoMethod: "ResetName"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetReadHeaders", GoMethod: "ResetReadHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetReadQueryParameters", GoMethod: "ResetReadQueryParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetReplaceTriggersExternalValues", GoMethod: "ResetReplaceTriggersExternalValues"},
			_jsii_.MemberMethod{JsiiMethod: "resetReplaceTriggersRefs", GoMethod: "ResetReplaceTriggersRefs"},
			_jsii_.MemberMethod{JsiiMethod: "resetResponseExportValues", GoMethod: "ResetResponseExportValues"},
			_jsii_.MemberMethod{JsiiMethod: "resetRetry", GoMethod: "ResetRetry"},
			_jsii_.MemberMethod{JsiiMethod: "resetSensitiveBody", GoMethod: "ResetSensitiveBody"},
			_jsii_.MemberMethod{JsiiMethod: "resetSensitiveBodyVersion", GoMethod: "ResetSensitiveBodyVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdateHeaders", GoMethod: "ResetUpdateHeaders"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdateQueryParameters", GoMethod: "ResetUpdateQueryParameters"},
			_jsii_.MemberProperty{JsiiProperty: "responseExportValues", GoGetter: "ResponseExportValues"},
			_jsii_.MemberProperty{JsiiProperty: "responseExportValuesInput", GoGetter: "ResponseExportValuesInput"},
			_jsii_.MemberProperty{JsiiProperty: "retry", GoGetter: "Retry"},
			_jsii_.MemberProperty{JsiiProperty: "retryInput", GoGetter: "RetryInput"},
			_jsii_.MemberProperty{JsiiProperty: "sensitiveBody", GoGetter: "SensitiveBody"},
			_jsii_.MemberProperty{JsiiProperty: "sensitiveBodyInput", GoGetter: "SensitiveBodyInput"},
			_jsii_.MemberProperty{JsiiProperty: "sensitiveBodyVersion", GoGetter: "SensitiveBodyVersion"},
			_jsii_.MemberProperty{JsiiProperty: "sensitiveBodyVersionInput", GoGetter: "SensitiveBodyVersionInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "updateHeaders", GoGetter: "UpdateHeaders"},
			_jsii_.MemberProperty{JsiiProperty: "updateHeadersInput", GoGetter: "UpdateHeadersInput"},
			_jsii_.MemberProperty{JsiiProperty: "updateQueryParameters", GoGetter: "UpdateQueryParameters"},
			_jsii_.MemberProperty{JsiiProperty: "updateQueryParametersInput", GoGetter: "UpdateQueryParametersInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
		},
		func() interface{} {
			j := jsiiProxy_DataPlaneResource{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-azapi.dataPlaneResource.DataPlaneResourceConfig",
		reflect.TypeOf((*DataPlaneResourceConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-azapi.dataPlaneResource.DataPlaneResourceRetry",
		reflect.TypeOf((*DataPlaneResourceRetry)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-azapi.dataPlaneResource.DataPlaneResourceRetryOutputReference",
		reflect.TypeOf((*DataPlaneResourceRetryOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "errorMessageRegex", GoGetter: "ErrorMessageRegex"},
			_jsii_.MemberProperty{JsiiProperty: "errorMessageRegexInput", GoGetter: "ErrorMessageRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "intervalSeconds", GoGetter: "IntervalSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "intervalSecondsInput", GoGetter: "IntervalSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxIntervalSeconds", GoGetter: "MaxIntervalSeconds"},
			_jsii_.MemberProperty{JsiiProperty: "maxIntervalSecondsInput", GoGetter: "MaxIntervalSecondsInput"},
			_jsii_.MemberProperty{JsiiProperty: "multiplier", GoGetter: "Multiplier"},
			_jsii_.MemberProperty{JsiiProperty: "multiplierInput", GoGetter: "MultiplierInput"},
			_jsii_.MemberProperty{JsiiProperty: "randomizationFactor", GoGetter: "RandomizationFactor"},
			_jsii_.MemberProperty{JsiiProperty: "randomizationFactorInput", GoGetter: "RandomizationFactorInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetIntervalSeconds", GoMethod: "ResetIntervalSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxIntervalSeconds", GoMethod: "ResetMaxIntervalSeconds"},
			_jsii_.MemberMethod{JsiiMethod: "resetMultiplier", GoMethod: "ResetMultiplier"},
			_jsii_.MemberMethod{JsiiMethod: "resetRandomizationFactor", GoMethod: "ResetRandomizationFactor"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DataPlaneResourceRetryOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-azapi.dataPlaneResource.DataPlaneResourceTimeouts",
		reflect.TypeOf((*DataPlaneResourceTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktn/provider-azapi.dataPlaneResource.DataPlaneResourceTimeoutsOutputReference",
		reflect.TypeOf((*DataPlaneResourceTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "read", GoGetter: "Read"},
			_jsii_.MemberProperty{JsiiProperty: "readInput", GoGetter: "ReadInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetRead", GoMethod: "ResetRead"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdate", GoMethod: "ResetUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "update", GoGetter: "Update"},
			_jsii_.MemberProperty{JsiiProperty: "updateInput", GoGetter: "UpdateInput"},
		},
		func() interface{} {
			j := jsiiProxy_DataPlaneResourceTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnComplexObject)
			return &j
		},
	)
}
